### ISSUE TITLE
Minecraft Cursor Snapping

### ISSUE THREAD

**Issue by junkmanner** [riverwm/river#656] opened 2022-07-21 13:47 UTC
This has already been mentioned in #594, however, in both legacy as well as the latest version of Minecraft, the cursor will randomly snap during gameplay. This can be reproduced through: pause > unpause > move mouse > click, but it also occurs randomly during gameplay, this occurs on both 0.1.3 and master, but not on sway.

Example:

https://user-images.githubusercontent.com/109739272/180229422-d99a9db3-70ac-4d2b-a3c7-cbad25145345.mp4

**Comment by ifreund** [comment] 2022-07-25 12:44
Thanks for the video, I think I'll close this as a duplicate of #594, there's no real reason to have two separate issues open.

**Closed by ifreund** 2022-07-25 12:44 UTC
