### ISSUE TITLE
touchpad malfunction after update

### ISSUE THREAD

**Issue by biscuitrescue** [riverwm/river#499] opened 2022-01-01 15:38 UTC
when i have a browser open and then try to open either another browser or something electron based like discord or signal, and then try to click on something, my touchpad acts on the first browser

**Comment by Leon-Plickat** [comment] 2022-01-01 16:41
I assume the browser and your electron applications are using XWayland?

**Comment by biscuitrescue** [comment] 2022-01-01 16:54
yes i think theyre using xwayland

**Comment by Leon-Plickat** [comment] 2022-01-01 21:12
Do you use multiple monitors? If yes, is one of those at negative coordinates?

**Comment by biscuitrescue** [comment] 2022-01-02 03:30
No, im sorry, i dont use multiple monitors

**Comment by ifreund** [comment] 2022-01-02 03:49
@biscuitrescue you say "after update" in the issue title. What version of river are you now using where this doesn't work and what version of river were you using before where it presumably did?

**Comment by biscuitrescue** [comment] 2022-01-02 03:54
im currently using the "river-0.1.2-1" and as far as i remember, it wasnt working for "0.1.0" either. The last version where it was working was before the zig 9.0 upgrade

**Comment by ifreund** [comment] 2022-01-02 04:04
> The last version where it was working was before the zig 9.0 upgrade

Do you mean that it was working on river 0.1.1?

**Comment by biscuitrescue** [comment] 2022-01-02 04:10
i dont exactly remember the version, but i remember that it worked with wlroots 14 and zig 8

**Comment by ifreund** [comment] 2022-01-02 04:35
Should be fixed by e16eabd9282e77c89e47874838443fb34150b56d, I don't think this ever worked properly in river.

Thanks for the report!

**Closed by ifreund** 2022-01-02 04:35 UTC
Labels: bug, xwayland

**Comment by j-james** [comment] 2022-01-21 04:00
Awesome, I also saw this, but couldn't figure out for the life of me exactly what the problem was or how to consistently reproduce it. Thanks for the fix!
