### ISSUE TITLE
river does not start when launched from SDDM

### ISSUE THREAD

**Issue by fislysandi** [riverwm/river#706] opened 2022-10-13 21:30 UTC
im basically trying out a wayland window manager that is similar to bspwm and im just having an issue to just making it even work. i installed arch with archinstall with a basic preset (minimal) on a virtual machine,btrfs.

and i installed it through AUR.it included -Dxwayland  in the build and when i reboot into my sddm and log into the session it shows the x cursor from xorg-xwayland for a split second then fucking dies and i cant ctrl + alt + f3 to switch non-graphical mode

why does this have to be so hard?

even after i removed -Dxwayland from PKGBUILD it still dies.

**Comment by fislysandi** [comment] 2022-10-13 21:51
wait i tried a different tiling window manager qtile same issue. why,am i cursed?

**Comment by Leon-Plickat** [comment] 2022-10-13 22:21
Note that display managers are not officially supported. Make sure your display manager properly supports Wayland sessions.

If you believe the fault to be on rivers side, then try launching river in a TTY with `river -log-level debu 2> log` to get a debug log.

**Comment by jiiiijiij** [comment] 2022-10-19 10:50
You can use greetd, I use it with tuigreet, after login it will boot me into TTY and I can run `river` command to boot into it. There other ways to run straight to river using greetd (Arch greetd wiki). But I like to have TTY as default.

**Comment by Leon-Plickat** [comment] 2022-10-19 11:06
Closing since this seems to be caused by the display manager. While we don't officially support DMs, river behaves well enough that any issue is likely the fault of the DM and not us.

I will re-open if this turns out to be an issue with river after all.

If you require further insight into settings up river with a DM, feel free to drop by on IRC (#river on libera chat) where some users seem to use a DM successfully and can probably help you out.

**Closed by Leon-Plickat** 2022-10-19 11:06 UTC
