### ISSUE TITLE
Clicking in fullscreen games causes mouse to snap

### ISSUE THREAD

**Issue by trypancakes** [riverwm/river#975] opened 2024-01-31 14:45 UTC
Occasionally when clicking the mouse in a fullscreen 3D game the mouse snaps. This usually results in the camera snapping downwards as much as possible but sometimes it's less intense. It's specifically when releasing left, middle, or right mouse button if that helps at all. This seems to be similar to #594 but I'm not sure if it's the same. I've tested and it happens with both Minecraft and Team Fortress 2 but probably other games as well. I'm using river 0.2.6 from nixpkgs. I've got a video of it happening twice https://youtu.be/wLMEmX0KHD0 (skip to 2:00)

**Comment by ifreund** [comment] 2024-01-31 17:40
The pointer constraints implementation has been completely rewritten since 0.2 and this bug may very well have been fixed on master branch already.

Does this reproduce on river's master branch? If so, I'm much more likely to be  able to debug and fix this if it is reproducible with an open source, or at least free and easy to obtain game.

**Comment by trypancakes** [comment] 2024-02-01 06:29
As it turns out getting master working on my setup was a pain because I'm newish to Nix but I did manage to try it. I did some testing with Minecraft and this doesn't seem to occur on master so I'm guessing the pointer constraints rewrite has fixed it. I'll probably switch back to stable in the meantime unless I decide to make a proper river-0.3.0-dev overlay or something.

**Closed** 2024-02-05 19:12 UTC
