### ISSUE TITLE
MPV window does not maintain aspect ratio of video being played

### ISSUE THREAD

**Issue by chcore** [riverwm/river#649] opened 2022-07-07 09:46 UTC
When resizing a floating MPV window in Sway, the dimensions are limited to preserve the aspect ratio of the video (i.e. it does not let you make the MPV window into a square if the video is widescreen). This is a nice little feature, and hope it can be implemented in river.

I have noticed that doing a `riverctl csd-filter-add app-id mpv` appears to achieve the desired behaviour, but I would like to preserve the window borders if possible.

**Comment by ifreund** [comment] 2022-07-07 10:31
Duplicate of #458

**Closed by ifreund** 2022-07-07 10:31 UTC
