### ISSUE TITLE
fullscreen filter

### ISSUE THREAD

**Issue by TAforever** [riverwm/river#715] opened 2022-11-04 16:07 UTC
Could you make the Telegram media viewer that appears when I click on any photo or video in Telegram automatically open in full screen mode, and not in tile mode, as is implemented in other tile wayland compositors and tile window managers X.

**Comment by ifreund** [comment] 2022-12-24 02:22
Duplicate of a couple other issues and implemented/fixed by 096e175ceca0b0ce313da58cd2d00b189f5ac458

**Closed by ifreund** 2022-12-24 02:22 UTC
Labels: enhancement
