### ISSUE TITLE
Set keyboard-layout for specific keyboard.

### ISSUE THREAD

**Issue by rcorre** [riverwm/river#943] opened 2023-12-28 20:29 UTC
I'd like to swap ctrl/alt on my laptop keyboard, but not on my external keyboard (which already has ctrl/alt swapped at a hardware level).
Currently I have:

```
# swap ctrl/alt and caps/esc for laptop keyboard, but not QMK keyboard
if ! riverctl list-inputs | grep Moonlander >/dev/null; then
    riverctl keyboard-layout -options caps:escape,ctrl:swap_lalt_lctl us
fi
```

That works fine when river starts up, but it doesn't handle disconnecting or connecting the keyboard at runtime. Is there any way to either:

- Detect a keyboard plug/unplug event and update the layout
- Scope a layout to a specific input name (similar to how `riverctl input` works)

It seems like sway [supports](https://github.com/swaywm/sway/wiki#input-configuration) this like so:

```
# default layout
input "1:1:AT_Translated_Set_2_keyboard" {
   xkb_layout us
}

# custom layout for an external keyboard
input "1452:591:Custom_Keyboard" {
   xkb_layout YourCustomLayout
}
```

**Comment by Leon-Plickat** [comment] 2023-12-29 06:43
Duplicate of #400

**Closed by Leon-Plickat** 2023-12-29 06:43 UTC
