### ISSUE TITLE
Can't use fcitx5 input method engine in Kitty on River

### ISSUE THREAD

**Issue by scotabroad** [riverwm/river#937] opened 2023-12-10 15:51 UTC
I can't even switch to another keyboard. Only English seems to be able to work, not my Chinese or IPA input methods. 

This works on any app that's not Kitty (Firefox, Gedit, etc.)

Also, I can use fcitx5 in Kitty on Hyprland.

**Comment by novakne** [comment] 2023-12-10 16:15
IME are not implemented in river yet, see #859

**Comment by ifreund** [comment] 2023-12-11 00:02
duplicate of #351

**Closed** 2023-12-11 00:02 UTC
