### ISSUE TITLE
Windows sometimes resize to their tiled dimensions when they lose focus while in fullscreen

### ISSUE THREAD

**Issue by isti115** [riverwm/river#968] opened 2024-01-19 23:24 UTC
I have started experiencing this issue a while ago, but didn't become annoyed enough to post about it until now. What happens sometimes is that when I put an application on fullscreen on one of my screens and move the focus to another monitor, the application on the original output restores it's dimensions to the geometry defined by the layout generator (but keeps it's position in the top left corner), as seen on the recording below:

[riverwm-fullscreen-focus-bug.webm](https://github.com/riverwm/river/assets/3758493/fb66eceb-c19e-4731-b5e7-f8a2d45556f2)

By experimenting, I have so far discovered that adjusting the `main-ratio` of `rivertile` can make the issue disappear, so I'm not sure whether this is a bug in `river` itself, or `rivertile`, but I would guess that `river` shouldn't allow fullscreen windows to change geometry, no matter what the layout generators are doing. Still, I'll try running a different layout generator for a while and report back if I find that the issue persists / disappears!

**Comment by Leon-Plickat** [comment] 2024-01-21 17:27
Which river version are you on? The behaviour of fullscreen windows loosing focus has changed on master.

There still is an issue with firefox and fullscreen which is easiely triggered by just having multiple firefox windows open, but that is a firefox bug, not a river bug.

**Comment by Isti115** [comment] 2024-01-22 18:33
I'm running a local build of `62dbe34b` with your `restore views to evacuated outputs on reconnect` commit cherry-picked on top. Is there any hope in waiting for the Firefox developers to address the issue, or should I try to look for a workaround if I'd like to stop this from happening?

**Comment by zgb124** [comment] 2024-01-23 03:44
I'm on master and seeing this with imv as well. You can reproduce it like this:

1. Open a terminal window
2. Use the terminal window to open an image file with imv
3. Make imv fullscreen
4. Move the mouse to another output

**Comment by Leon-Plickat** [comment] 2024-01-23 13:12
Note that imv is not a well behaved client either.

**Comment by isti115** [comment] 2024-02-18 15:07
Just in case anyone else is facing this same issue, I'll share that in the meantime I have found the `monocle` layout provided by [`rivercarro`](https://sr.ht/~novakane/rivercarro) to be a perfectly reasonable workaround by making application windows take up entire outputs while avoiding entering true fullscreen mode.

**Comment by ifreund** [comment] 2024-02-19 13:25
Is this still reproducible for anyone with firefox since commit a531311ac6a44fef2b0ba5c662c0ec243d63778f?

**Comment by ifreund** [comment] 2024-02-25 16:20
Thanks for letting me know, I guess I'll close this issue then though feel free to reopen or open a new issue if you have problems again :)

**Closed by ifreund** 2024-02-25 16:20 UTC
Labels: can't reproduce
