### ISSUE TITLE
Move view to currently active tag(s) on the output after send-to-output

### ISSUE THREAD

**Issue by chcore** [riverwm/river#643] opened 2022-07-01 23:40 UTC
On my left monitor I have tag A active with a web browser open, on my right monitor I have tag Z active with nothing on it. I move the browser window from the left monitor to the right monitor with send-to-output. This works, but it arrives on tag A on the right monitor instead of the currently active tag (tag Z).

Is it possible to have it arrive on which ever tag(s) is active so that I do not need to switch tags, move the view and then switch back? Thanks

**Comment by ElJeffe** [comment] 2022-07-12 13:17
this is also the behavior in AwesomeWM, and it feels more natural.

**Comment by Aiz0** [comment] 2022-07-12 20:06
This issue is a duplicate of https://github.com/riverwm/river/issues/457

**Closed** 2022-07-12 20:21 UTC
Labels: duplicate
