### ISSUE TITLE
keep newly opened floating window on top of other floating window

### ISSUE THREAD

**Issue by AtifChy** [riverwm/river#406] opened 2021-08-27 09:15 UTC
When you have multiple floating windows open, then It becomes hard to focus on a newly opened floating window with mouse (``focus-follows-cursor`` enabled). It becomes even harder to focus on the window when it opens up on a floating window, which is bigger. You can't even focus it without resizing or moving the bigger window somewhere else.

**Comment by Meister1593** [comment] 2021-08-28 11:30
> > > some gui apps need it.
> > 
> > 
> > @AtifChy This is really not helpful without an example of a "gui app" you think needs it and an explanation of why you think said program needs it.
> 
> vid_2021-08-27_21-27-12.mp4

this is quite annoying indeed

**Comment by pranjlp** [comment] 2021-10-18 08:34
Just want to add that this is also annoying if you move windows between tags.. like the scratchpad implementation in the wiki.

if there is a floating window or a full screen window already open in your current tag. Moving the scratchpad window to the current tag puts it in the bottom of the stack of floating/fullscreen windows respectively.

**Comment by tgy** [comment] 2023-12-26 21:34
i confirm this is a really surprising and annoying behaviour. sometimes i create a new window and it ends behind all existing floating windows. i really thought this was a bug

**Comment by ifreund** [comment] 2024-02-19 22:48
Closing this as a duplicate of https://github.com/riverwm/river/issues/982, the discussion there is higher quality.

**Closed by ifreund** 2024-02-19 22:48 UTC
