### ISSUE TITLE
Some fullscreen windows dont show

### ISSUE THREAD

**Issue by Anachron** [riverwm/river#898] opened 2023-11-02 12:46 UTC
Running `zathura --mode=fullscreen cmp/present.pdf` does unfocus the terminal and lets me run commands on the Windows, but I can't see the window and can only bring it back by exiting fullscreen (F11).

Running zathura in normal mode `zathura cmp/present.pdf` and switching to the fullscreen mode does however work as expected.

It seems like this is an issue with opening apps (like zathura) directly in fullscreen.

Edit:
Other applications, like `foot -F`, work as expected.

Edit2:
I am on `river-0.2.4_2` & `zathura-0.5.2_1`.

**Comment by Anachron** [comment] 2023-11-02 12:57
I'm happy to assist helping you geting to the root of the issue, if there is something I can do, please let me know!

**Comment by justinesmithies** [comment] 2023-11-02 21:15
Strange as running `zathura --mode=fullscreen Downloads/test.pdf` works fine for me. I am using the git master version so it's `0.3.0-dev.141+5da4769`

**Comment by ifreund** [comment] 2023-11-02 22:48
Closing as this bug report is against 0.2.4 and does not seem to be reproducible on master branch. So much has changed internally since 0.2.4 that I can't say exactly what caused or fixed this.

If anyone can reproduce this on master branch let me know and I'll reopen this.

**Closed by ifreund** 2023-11-02 22:48 UTC

**Comment by Anachron** [comment] 2023-11-03 09:30
Can confirm, issue does not happen on `0.3.0-dev.141+5da4769`.

**Comment by uncomfyhalomacro** [comment] 2023-11-03 10:42
I can confirm. This does not happen on my build as well on openSUSE. I follow the master branch closely (not recent commit but it works)
