### ISSUE TITLE
River ignores cursor movements when resizing slow windows

### ISSUE THREAD

**Issue by vainiovano** [riverwm/river#812] opened 2023-03-24 06:55 UTC
Because of how river currently ties cursor movement to floating window resizes, the speed of resizing a window depends on which window is being resized and what the application is doing. mpv's resizing speed changes quite a lot depending on whether the video is paused or not:

https://user-images.githubusercontent.com/16741932/227445727-ffec8f13-5808-4f67-b20a-2eaca86a45be.mp4

The same thing happens with Firefox too which resizes faster when the window is smaller.

**Comment by vainiovano** [comment] 2023-03-28 14:26
This (or a similar cause) also makes it very difficult to resize a floating gnome-terminal which only resizes to integer multiples of cell width when floating, which is allowed by the protocol. Even the tiniest pointer movements cause the window to reduce rapidly in size while the window can only be made bigger by moving the cursor pretty quickly.

**Comment by ifreund** [comment] 2023-03-28 22:16
I'm working on a branch that should hopefully fix this.

**Comment by ifreund** [comment] 2023-07-21 17:26
It looks like chromium with it's native wayland ozone backend is also affected by this.

**Comment by ifreund** [comment] 2023-10-17 17:19
A relatively straightforward and noninvasive fix for this occurred to me so I just pushed f364e1b81b482465978cd5fdacbc32dbfa37534d. 

I don't know why I didn't think of it last time I looked at this, but oh well.

If anyone can still reproduce this please let me know, how exactly this resizing feels depends a lot on how fast the graphics hardware is.

**Closed by ifreund** 2023-10-17 17:19 UTC
Labels: bug
