### ISSUE TITLE
River stops responding to mouse clicks and hovers after output disconnect

### ISSUE THREAD

**Issue by 0xfea5** [riverwm/river#961] opened 2024-01-09 09:32 UTC
I am currently running a dual monitor setup and run into a bug that makes mouse clicks and hovers unresponsive.

Ways to reproduce this:

1) Start river with both monitors on
2) Turn off my left monitor (turning off the right produces another bug which I may explain on a separate issue)
3) Now river would no longer respond to mouse clicks and hovering over any window would not focus it (that only makes sense when focus-follows-cursor is not disabled).

I can take a look into it but I open the issue in case anyone else can reproduce this and help fixing it. Also, since I am new to wayland, how can I generate a log of wayland events?

**Comment by ifreund** [comment] 2024-01-09 18:18
What river version/commit are you running?

**Comment by 0xfea5** [comment] 2024-01-09 20:23
@ifreund I am running the latest master

**Comment by ifreund** [comment] 2024-02-23 13:56
This issue could really use at least a debug log from river, `river -log-level debug >river.log 2>&1`.

I still can't reproduce this, currently using river version `0.3.0-dev.232+f2b6893`.

**Comment by ifreund** [comment] 2024-02-25 12:54
Ah, I can reproduce this without kanshi running, I think I know what's happening here.

**Comment by ifreund** [comment] 2024-02-25 13:40
Should be fixed by 0605ce507e9eeef62f7047a76c4a8b586f8ff60a

**Closed by ifreund** 2024-02-25 13:40 UTC
Labels: bug

**Comment by 0xfea5** [comment] 2024-02-26 00:40
> Should be fixed by [0605ce5](https://github.com/riverwm/river/commit/0605ce507e9eeef62f7047a76c4a8b586f8ff60a)

Sorry for not replying earlier, after upgrading it seems to be fixed, thank you!
