### ISSUE TITLE
Menu in Firefox breaks if window is too big

### ISSUE THREAD

**Issue by Osrepnay** [riverwm/river#690] opened 2022-09-10 17:19 UTC
(somewhat) Recently I've found that if Firefox's main window is too big, then opening the hamburger menu thing in the top right corner no longer works. It'll work the first time, but after that it becomes invisible.
Logs are from opening Firefox from `river -log-level debug -c "MOZ_ENABLE_WAYLAND=1 firefox" > file 2>&1` and then clicking the menu once, clicking outside to close it, clicking it again, closing it (I think, might have forgotten to close it in some of them), then killing river because I can't use a shortcut to close it

Logs with correct menus because -c spawns it in a small rectangle usually: https://0x0.st/ofUR.txt
Logs with invisible menu on the second click because when Firefox opens the troubleshoot dialog after being killed and you click "Open", Firefox opens a larger window: https://0x0.st/ofU5.txt

**Comment by dkwo** [comment] 2022-09-10 19:26
Could you check whether https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3446 fixes this?

**Comment by Osrepnay** [comment] 2022-09-10 20:33
Sorry, idk how to use that commit :/ it looks like it's 0.16 and renaming the version froze my computer after building and running river

**Comment by Osrepnay** [comment] 2022-09-11 03:46
uh well it works now... as well as tooltips (which had a similar problem)... I'll get back if it breaks again, I have no idea what I did that fixed it

**Comment by sagehane** [comment] 2022-09-22 14:56
I've been able to reproduce this issue (or a similar one that causes visual issues and crashes Firefox) by making the bookmark toolbar visible with Shift + Ctrl + B, making a bookmark folder, and adding as many bookmarks into that folder until all the bookmarks span the entire screen vertically.

**Comment by Leon-Plickat** [comment] 2022-09-22 16:32
Whoops, apparently I missed this issue in my weekly triage checks, sorry everyone.

Either way, I unfortunately can't reproduce. It is known that firefox does uncommon and weird things with subsurfaces and xdg-popups, but the problem may be with wlroots and not river.

Since rivers rendering and surface handling code will be switched to the upcoming wlroots scene graph (although probably not this year) it makes the most sense IMO to wait and see if that will fix the issue.

**Comment by sagehane** [comment] 2022-09-22 16:43
Oh well, the only other relevant things I can think of is that I have fractional scaling set to 1.5.

My disto is:
```sh-session
$ nixos-version
22.11.20220918.f677051 (Raccoon)
```
and my river version is `c0e64829f0517f6512438cbf80ae27bd21986b47` (compiled from source) but I doubt either really matter because I've been reproducing this successfully for at least a month now.

**Comment by novakne** [comment] 2022-09-22 16:51
I have these problems since Firefox 100, as this time, looking around Firefox and wlroots bugs reports, it seems all or most of these bugs should be fixed with wlroots 0.16

**Comment by ifreund** [comment] 2022-11-25 13:23
Closing this as fixed by upgrading to wlroots 0.16.0.

**Closed by ifreund** 2022-11-25 13:23 UTC
Labels: can't reproduce
