### ISSUE TITLE
Wacom tablet doesn't work

### ISSUE THREAD

**Issue by snakedye** [riverwm/river#162] opened 2020-11-29 16:02 UTC
It works properly on Sway and Wayfire but not on River.

**Comment by ifreund** [comment] 2020-11-29 16:21
Tablet support is not yet implemented.

**Comment by edrex** [comment] 2021-01-08 21:50
My laptop (dell xps 13 9360 QHD) has a touchscreen which I occasionally remember exists and use to draw something. I'd def be willing to help test, and maybe also to contribute patches although it's only #nicetohave for me.

**Comment by edrex** [comment] 2021-01-08 21:52
This depends on #71

**Comment by ap29600** [comment] 2021-04-11 14:37
Is this being worked on? I would love to contribute but I don't know any zig, so you're going to have to wait a while for a patch by me.

Tablet support is basically the only thing preventing me from using river full-time, which would be very nice.

**Comment by wizardwatch** [comment] 2021-09-18 00:57
I see https://github.com/ifreund/river/pull/303 has been merged. Is it within the scope of the current configuration method to allow tablet configuration? If it is, how hard would it be to implement that having little familiarity with Zig and Libinput?

**Comment by Leon-Plickat** [comment] 2021-09-18 03:28
> Is it within the scope of the current configuration method to allow tablet configuration?

It is. But the issue is not missing tablet configuration support. Tablets are currently not supported *at all*. As in, river will completely ignore these devices.

If you want tablets to work on river, configuration is the last thing you'd have to worry about. It's actually not hard to implement it, someone just needs to put the time and work in.

**Comment by novakne** [comment] 2021-09-18 15:33
First step would be to bind wlroots headers files for tablet in zig wlroots I guess, unless I missed something and you could do just with libinput

**Comment by Norkkiii** [comment] 2021-12-16 12:06
Some tablets can be used with OpenTabletDriver as a workaround for now.

**Comment by novakne** [comment] 2022-01-13 09:41
There is a PR (https://github.com/swaywm/zig-wlroots/pull/35) for the bindings though.

**Comment by antaxiom** [comment] 2022-01-13 10:06
Thanks, I simply don't have the knowledge to implement it so I can't do
much there.

**Comment by ifreund** [comment] 2024-02-27 10:40
I've just added tablet-v2 bindings to zig-wlroots which unblocks the implementation in river: https://codeberg.org/ifreund/zig-wlroots/commit/9b658391d3436a28ef85087897cc01c0c9ceca48

**Comment by ifreund** [comment] 2024-03-11 16:26
Tablet pad support is tracked in #1021.

I don't have any plans to work on it at the moment due to lack of hardware. If anyone is interested in that feature and has hardware that could be used to test it please leave a comment there.

**Closed by ifreund** 2024-03-11 16:26 UTC
Labels: enhancement
