### ISSUE TITLE
Crash in XwaylandView.handleDissociate

### ISSUE THREAD

**Issue by Kirottu** [riverwm/river#963] opened 2024-01-11 09:51 UTC
Seemingly sometimes with some Xwayland windows (Duck Game automatic restart in this case), the latest master builds can crash with river aborting in that function when the window is closed. Hasn't happened every time though.

**Comment by ifreund** [comment] 2024-01-11 17:43
This issue could really use a full stack trace and debug river log, I don't own duck game and can't reproduce this myself

**Comment by ifreund** [comment] 2024-01-24 23:03
This could perhaps be related to https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4524 which will be included in the wlroots 0.17.2 bugfix release.

**Comment by ifreund** [comment] 2024-01-25 12:44
Having looked at the code in a bit more depth, I'm pretty sure the wlroots bug that patch fixes is the cause of this crash. It looks like it can cause the dissociate event to be emitted without a matching associate having been sent. This issue can be closed when wlroots 0.17.2 is released and required by river.

**Comment by ifreund** [comment] 2024-03-11 18:16
wlroots 0.17.2 has been released :)

**Closed by ifreund** 2024-03-11 18:16 UTC
Labels: bug, upstream, crash, xwayland
