### ISSUE TITLE
Issue with XDG window geometry when moving resizing

### ISSUE THREAD

**Issue by Leon-Plickat** [riverwm/river#748] opened 2022-12-31 01:12 UTC
Moving / resizing a view with a window geometry not matching the surface size makes the output constraints apply incorrectly. The effective size of the view is then the buffer/surface size, simply moved by the position of the window geometry.

![river](https://user-images.githubusercontent.com/49593314/210120598-f63c6f09-e56c-4e49-b573-aba61e1ecc8e.png)

**Comment by Leon-Plickat** [comment] 2022-12-31 01:13
At least with an shm testing client. GTK4 windows also use xdg-window geometry, but behave correctly.

**Comment by Leon-Plickat** [comment] 2022-12-31 01:23
For reference:

Here is the shm client:

![image](https://user-images.githubusercontent.com/49593314/210120856-37e6449d-cb2f-455b-ba67-0dcbdfce32d7.png)

And the GTK4 client:

![image](https://user-images.githubusercontent.com/49593314/210120869-c2154372-c767-4be7-9a32-97de54d00b85.png)

**Comment by ifreund** [comment] 2022-12-31 17:44
I'm having trouble reproducing this. Could you share your shm test client?

**Comment by MaxVerevkin** [comment] 2022-12-31 17:56
Sorry for off-topic but which tool is used on these screenshots?

**Comment by Leon-Plickat** [comment] 2022-12-31 17:58
@MaxVerevkin https://git.sr.ht/~kennylevinsen/wlhax

**Comment by ifreund** [comment] 2022-12-31 19:20
The issue here seems to only occur when the client does not respect the size requested by river in the xdg_toplevel.configure event. For example, everything works properly with this alternative patch to [snayk](https://git.sr.ht/~leon_plickat/snayk). The screenshot above is with a snayk version that adds only the xdg_surface_set_window_geometry() call which results in a mismatch with the dimensions requested by river.
```diff
diff --git a/snayk.c b/snayk.c
index 3ed7d1b..40259a7 100644
--- a/snayk.c
+++ b/snayk.c
@@ -917,6 +917,8 @@ static void xdg_surface_handle_configure (void *data, struct xdg_surface *xdg_su
                wl_surface_set_opaque_region(view->wl_surface, region);
                wl_region_destroy(region);
 
+               xdg_surface_set_window_geometry(view->xdg_surface, 20, 20, ((int32_t)view->next_width - 40), ((int32_t)view->next_height - 40));
+
                view->field = new_field_dimensions();
                render_frame();
                wl_surface_commit(view->wl_surface);
@@ -952,8 +954,8 @@ static void xdg_toplevel_handle_close (void *data, struct xdg_toplevel *xdg_topl
 static void xdg_toplevel_handle_configure (void *data, struct xdg_toplevel *xdg_toplevel,
                int32_t width, int32_t height, struct wl_array *states)
 {
-       view->next_width  = (uint32_t)width;
-       view->next_height = (uint32_t)height;
+       view->next_width  = (uint32_t)width + 40;
+       view->next_height = (uint32_t)height + 40;
        view->next_focused = false;
        view->next_fullscreen = false;
        enum xdg_toplevel_state *state;
```

**Comment by ifreund** [comment] 2023-01-08 14:35
This is somewhat a duplicate of #519.

**Comment by ifreund** [comment] 2023-03-10 21:22
I believe this should be fixed since the switch to the wlroots scene graph and transaction system refactor. If not please drop a comment here and I'll reopen it and take another look.

**Closed by ifreund** 2023-03-10 21:22 UTC
