### ISSUE TITLE
Can't use screen locking softwares after the update

### ISSUE THREAD

**Issue by MelihDarcanxyz** [riverwm/river#758] opened 2023-01-05 18:19 UTC
After river 0.2 update I can't run any of the following screen locking softwares:

## waylock:
```
thread 'main' panicked at '[SCTK] A missing global was required: zwlr_input_inhibit_manager_v1', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.15.3/src/environment.rs:193:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## gtklock:
```
** (gtklock:38102): CRITICAL **: 21:15:42.023: Your compositor doesn't support wlr-input-inhibitor
```
This might be due to fact that gtklock doesn't comply with ```ext-session-lock-v1```

## swaylock:
Full black screen with no way to interact with anything. I had to switch to tty2 and kill river.

**Comment by adamcstephens** [comment] 2023-01-05 18:32
I suspect this will need to be fixed on the gtklock side. It's good that you opened an issue there https://github.com/jovanlanik/gtklock/issues/53

**Comment by MelihDarcanxyz** [comment] 2023-01-05 18:35
Not just gtklock, I've tested for swaylock and waylock too. None of them work. I also added what happens with them too.

**Comment by adamcstephens** [comment] 2023-01-05 18:53
What version of waylock did you try? There was a release of 0.5.0 a few days ago.

**Comment by MelihDarcanxyz** [comment] 2023-01-05 19:07
I'm using ```waylock 0.3.5```. Appearantly arch package is outdated. Will test it when it gets updated.
According to README, waylock has been entirely rewritten with the new protocol. That makes sense since river's developer has developed that screen-locked and the new protocol.

 But still, I can't understand swaylock's behavior since it does support the new protocol.

**Comment by Leon-Plickat** [comment] 2023-01-05 19:31
This is not a bug, support for input inhibitor was dropped on purpose. It is a bad way to implement screenlockers and has been replaced by the dedicated screen locking protocol. waylock has a recent new release which supports it. The old rust based version of waylock will no longer function with river.

**Closed by Leon-Plickat** 2023-01-05 19:31 UTC

**Comment by MelihDarcanxyz** [comment] 2023-01-05 19:59
I understand that but swaylock does not work. I explained the behavior. It was working before the update.
