### ISSUE TITLE
River turns off numlock on launch

### ISSUE THREAD

**Issue by Sprite36** [riverwm/river#478] opened 2021-11-24 19:21 UTC
I'm trying to use numlock after launch and it is really annoying to manually turn it on. Is there any solution? I turn on numlock automatically using sddm.

**Comment by novakne** [comment] 2021-11-24 19:27
No, see #407

**Comment by Sprite36** [comment] 2021-11-24 19:34
Yeah I saw this but there is no way I know of to enable it in wayland with openrc. I have to stay doing things manually then.

**Comment by Leon-Plickat** [comment] 2021-11-24 22:18
Closing as this is a duplicate of #407.

**Closed by Leon-Plickat** 2021-11-24 22:18 UTC
