### ISSUE TITLE
When screens resume, all windows move to one output

### ISSUE THREAD

**Issue by ElJeffe** [riverwm/river#675] opened 2022-08-17 08:38 UTC
Hi,
I have a dual screen setup and I use `swayidle` in combination with `wlopm` to turn my screens of after a certain time:
```
riverctl spawn 'swayidle -w timeout 300 "wlopm --off \"*\"" resume "wlopm --on \"*\""'
```
When I wake up the screens, all the windows of the two screens move to the screen of my laptop.
I noticed that my external screen goes to standby after 15s, and can reproduce also with
```
wlopm --off "*"; sleep 20; wlopm --on "*"
```

The issue is that on resume, the system thinks that there is only one display available and moves all windows to this one display, and some seconds later, the external display awakens and is present again.
A log from kanshi seems to confirm this:
```
applying profile 'home'
applying profile output 'eDP-1' on connected head 'eDP-1'
applying profile output 'DP-1' on connected head 'DP-1'
running commands for configuration 'home'
configuration for profile 'home' applied
applying profile 'home'
-> wlopm --off

->wlopm --on
applying profile 'alone'
applying profile output 'eDP-1' on connected head 'eDP-1'
running commands for configuration 'alone'
configuration for profile 'alone' applied
applying profile 'home'
applying profile output 'DP-1' on connected head 'DP-1'
applying profile output 'eDP-1' on connected head 'eDP-1'
running commands for configuration 'home'
configuration for profile 'home' applied
applying profile 'home'
```
I know riverwm just does what it should do when it thinks that there is only one display connected, but it is not the expected behavior from a user point of view.

**Comment by chcore** [comment] 2022-08-19 06:59
I am also experiencing this, and is probably the biggest issue I am having with river on a day to day basis (right behind not being able to assign a tag and window position on the screen with riverctl spawn). Hope there will be a solution.

**Comment by Leon-Plickat** [comment] 2022-08-19 07:01
Duplicate of #666

**Closed by Leon-Plickat** 2022-08-19 07:01 UTC
